### ISSUE TITLE
is there a tool to convert HHblits output to profile file?

### ISSUE THREAD

**Issue by jjlex** [compbiomed-unito/acdc-nn#2]

**Comment by Xinheng-He** [comment]
Hi bro, I wrote one on my Github. You can find it at https://github.com/Xinheng-He/psi_to_prof_for_acdc. psi file is one of the outputs for hhlits. Just use as python psi_to_prof.py omi.psi omi.prof.

**Comment by gbirolo** [comment]
Sorry for the late reply, I added instructions on profile creation at the end of the README file.
